spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    ddl-auto: create-drop
  datasource:
    url: jdbc:sqlite:memory:myDb
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
