jwt:
  secret: testtesttesttesttesttest
spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:sqlite:test.db
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
