jwt:
  secret: ${JWT_SECRET}
spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlite:${DBPATH}
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type: TRACE
