spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlite:/home/aonufrei/Work/learn-de-db
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
