name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build and install
      run: mvn clean install
    - name: Upload application
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "./target/"
        target: "/home/${{secrets.SSH_USER}}/learnde-app/"
    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{secrets.WORKSPACE}}
          systemctl stop learnde.service
          rm ./app.jar
          mv ./target/learn-de-0.0.1-SNAPSHOT.jar ./app.jar
          rm -rf ./target
          systemctl start learnde.service